config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get    '/login' => 'session#new', as: "login"
  post   '/login' => 'session#create', as: "login_create"
  delete '/logout' => 'session#destroy', as: "logout"
  post "contact_us" => "home#contact_us", as: "save_contact_us"
  get "products/:permalink" => "home#product_detail", as: "product_detail"
  get 'tentang-kompor-induksi' => 'home#kompor_induksi', as: "kompor_induksi"

  get "admin" => "admin/dashboard#index", as: "admin"
  namespace :admin do
    resources :banners
    resources :categories
    resources :products do
      member do
        resources :product_images, except: [:index], param: :product_image_id
        get "product_images/:product_image_id/set_as_primary" => "product_images#set_as_primary", as: "set_as_primary"
        resources :product_feature_details, param: :product_feature_detail_id
      end
    end
  end

  root to: "home#index"
end

app/models/banner.rb
class Banner < ApplicationRecord
  TYPE = [["mobile", "mobile"], ["web", "web"]]
  mount_uploader :image, BannerUploader

  validates_presence_of :image
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < Admin::ApplicationController
  before_action :find_banner, :only => [:edit, :update, :destroy, :delete]

  def index
    @banners = Banner.page(params[:page]).per(20)
    @no = paging(20)
  end

  def new
    @banner = Banner.new
    @types = Banner::TYPE
  end

  def create
    @banner = Banner.new(banner_params)
    if @banner.save
      flash[:notice] = 'Banner was successfully create.'
      redirect_to admin_banners_path
    else
      @types = Banner::TYPE
      flash[:error] = "Banner failed to create"
      render :action => :new
    end
  end

  def edit
    @types = Banner::TYPE
  end

  def update
    if @banner.update_attributes(banner_params)
      flash[:notice] = 'Banner was successfully updated.'
      redirect_to admin_banners_path
    else
      @types = Banner::TYPE
      flash[:error] = "Banner failed to update"
      render :action => :edit
    end
  end

  def destroy
    flash[:notice] =  @banner.destroy ? 'Banner was successfully deleted.' :
                                        'Banner was falied to delete.'
    redirect_to admin_banners_path
  end

  private

    def banner_params
      params.require(:banner).permit(:image, :url, :alt, :b_type )
    end

    def find_banner
      @banner = Banner.find_by_id(params[:id])
      if @banner.nil?
        flash[:notice] = "Cannot find the Banner with id '#{params[:id]}'"
        redirect_to admin_banners_path
      end
    end
end

app/views/admin/banners/_form.html.erb
<%# content_for :javascript_includes do %>
  <%#= javascript_include_tag "/assets/ckeditor/ckeditor" %>
<%# end %>

<%= simple_form_for [:admin, @banner], html: {multipart: true}, wrapper: :horizontal_form,
                    wrapper_mappings: { file: :horizontal_file }  do |f| %>
  <%= f.error_notification %>
  <%= f.input :b_type, collection: @types %>
  <%= f.input :image, as: :file  %>
  <div class="form-group row file optional input-note">
    <label class="col-sm-3 form-control-label file optional">&nbsp;</label>
    <div class="col-sm-9 input-note">please upload image with size 1500px x 469px (width x height)</div>
  </div>
  <%#= f.input :url %>
  <!--
  <div class="form-group row file optional input-note">
    <label class="col-sm-3 form-control-label file optional">&nbsp;</label>
    <div class="col-sm-9 input-note">e.g www.google.com (without http://)</div>
  </div>-->
  <%= f.input :alt %>
  <div class="form-group row mb-0">
    <div class="col-sm-9 offset-sm-3">
      <%= f.button :submit, class: "btn-primary" %>
      <%= link_to "Cancel", admin_banners_path(:page => params[:page]), 
                  class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

app/views/admin/banners/edit.html.erb
<section class="admin-section-content">
  <div class="container">
    <div class="row">
      <div class="col-12 header-n-breadcrumb">
        <div class="row">
          <div class="col-12 col-md-6">
            <h2>Edit Banner</h2>
          </div>
          <div class="col-12 col-md-6 align-self-center">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
                <li class="breadcrumb-item"><%= link_to "banners", admin_banners_path %></li>
                <li class="breadcrumb-item active" aria-current="banner">Edit</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
      <div class="col-sm-12 admin-banners">
        <%= render :partial => "shared/flash" %>
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/admin/banners/index.html.erb
<section class="admin-section-content">
  <div class="container">
    <div class="row">
      <div class="col-12 header-n-breadcrumb">
        <div class="row">
          <div class="col-12 col-md-6">
            <h2>BANNER</h2>
          </div>
          <div class="col-12 col-md-6 align-self-center">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
                <li class="breadcrumb-item active" aria-current="banner">Banners</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
      <div class="col-sm-12 admin-banners">
        <%= render :partial => "shared/flash" %>
        <p> <%= link_to "Add new banner", new_admin_banner_path, class: "btn btn-primary" %></p>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>Image</th>
              <th>alt</th>
              <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody>
            <% @banners.each_with_index do |banner, x| %>
              <tr>
                <th scope="row"><%= @no+x+1 %></th>
                <td><%= image_tag banner.image.url(:thumb) %></td>
                <td><%= banner.alt %></td>
                <td>
                  <%= link_to "Edit", edit_admin_banner_path(banner.id), :class => "btn btn-success" %>
                  <%= link_to "Delete", admin_banner_path(banner.id), :method => :delete,
                                        data: {:confirm => "Are you sure?"}, :class => "btn btn-danger" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <div class="col-xs-12 pagination justify-content-center"><%= paginate @banners %></div>
      </div>
    </div>
  </div>
</section>

app/views/admin/banners/new.html.erb
<section class="admin-section-content">
  <div class="container">
    <div class="row">
      <div class="col-12 header-n-breadcrumb">
        <div class="row">
          <div class="col-12 col-md-6">
            <h2>New Banner</h2>
          </div>
          <div class="col-12 col-md-6 align-self-center">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
                <li class="breadcrumb-item"><%= link_to "banners", admin_banners_path %></li>
                <li class="breadcrumb-item active" aria-current="banner">New</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
      <div class="col-sm-12 admin-banners">
        <%= render :partial => "shared/flash" %>
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</section>