config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get    '/login' => 'session#new', as: "login"
  post   '/login' => 'session#create', as: "login_create"
  delete '/logout' => 'session#destroy', as: "logout"
  post "contact_us" => "home#contact_us", as: "save_contact_us"
  get "products/:permalink" => "home#product_detail", as: "product_detail"
  get 'tentang-kompor-induksi' => 'home#kompor_induksi', as: "kompor_induksi"

  get "admin" => "admin/dashboard#index", as: "admin"
  namespace :admin do
    resources :banners
    resources :categories
    resources :products do
      member do
        resources :product_images, except: [:index], param: :product_image_id
        get "product_images/:product_image_id/set_as_primary" => "product_images#set_as_primary", as: "set_as_primary"
        resources :product_feature_details, param: :product_feature_detail_id
      end
    end
  end

  root to: "home#index"
end

app/models/product.rb
class Product < ApplicationRecord
  serialize :compatibility, Array
  COMPATIBILITY = ["Kompor Induksi", "Kompor Gas", "Kompor Listrik", 
                   "Panci 68", "Panci K655 K625", "Wajan 68"]

  has_permalink :name, :update => true

  has_many :product_images, inverse_of: :product
  has_many :product_feature_details, inverse_of: :product

  belongs_to  :category

  validates :name, presence: true
  validates :short_description, presence: true

  accepts_nested_attributes_for :product_images, allow_destroy: true

  def category_name
    self.try(:category).try(:name)
  end

  def image(size)
    img = self.product_images.first
    if img.nil?
      return "/assets/no-image-yet.jpg"
    else
      return img.image.url(size.to_sym)
    end
  end

  def primary_image
    img = self.product_images.where("is_primary is not null and is_primary = true").first
    img = self.product_images.first if img.nil?
    if img.nil?
      return "/assets/no-image-yet.jpg"
    else
      puts img.inspect
      return img.image.url(:medium)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_action :find_product, :only => [:edit, :update, :destroy]
  before_action :validate_page, :only => [:update, :destroy]

  def index
    @products = Product.all.page(params[:page]).per(20)
    @no = paging(20)
  end

  def new
    @product = Product.new
    @categories = Category.all
    @product.product_images.build
    @compatibility = Product::COMPATIBILITY
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'product was successfully create.'
      redirect_to admin_products_path
    else
      @categories = Category.all
      @product.product_images.build
      @compatibility = Product::COMPATIBILITY
      flash[:error] = "product failed to create"
      render :action => :new
    end
  end

  def edit
    @categories = Category.all
    if @product.product_images.blank?
      @product.product_images.build
    end
    @compatibility = Product::COMPATIBILITY
  end

  def update
    if @product.update_attributes(product_params)
      flash[:notice] = 'product was successfully updated.'
      redirect_to admin_products_path(page: params[:product][:page])
    else
      @categories = Category.all
      if @product.product_images.blank?
        @product.product_images.build
      end
      @compatibility = Product::COMPATIBILITY
      flash[:error] = "product failed to update"
      render :action => :edit
    end
  end

  def destroy
    flash[:notice] =  @product.destroy ? 'product was successfully deleted.' :
                                           'product was falied to delete.'
    redirect_to admin_products_path(page: params[:product][:page])
  end

  private

    def product_params
      params.require(:product).permit(:name, :price, :short_description, :description,
                                      :specification, :feature, :category_id, compatibility: [],
                                      product_images_attributes: [:id, :image, :_destroy])
    end

    def find_product
      @product = Product.find_by_id(params[:id])
      if @product.nil?
        flash[:notice] = "Cannot find the product with id '#{params[:id]}'"
        redirect_to admin_products_path
      end
    end

    def validate_page
      params[:product][:page] = params[:product][:page].to_i <= 0 ? 1 : params[:product][:page]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find_by_permalink(params[:cat_permalink])
    if @category.nil?
      (redirect_to root_path) if Category.default_category.nil?
      redirect_to products_path(Category.default_category.id)
    end
    @products = @category.products
    @categories = Category.parent_categories 
  end

  def show
    @category = Category.find_by_permalink(params[:cat_permalink])
    if @category.nil?
      @category = Category.default_category
      (redirect_to root_path) if @category.nil?
      redirect_to products_path(@category.permalink)
    end

    @product = @category.products.find_by_permalink(params[:permalink])
    if @product.nil?
      redirect_to products_path(@category.permalink) 
    end
    @product_images = @product.product_images

  end
end

app/views/admin/products/_form.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "/assets/ckeditor/ckeditor" %>
<% end %>

<%= simple_form_for [:admin, @product], wrapper: :horizontal_form, 
                    wrapper_mappings: { 
                      check_boxes: :horizontal_collection, 
                      file:          :horizontal_file } do |f| %>
  <%= f.error_notification %>
  <%= f.input :category_id, collection: @categories %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%#= f.input :compatibility, :as => :hidden %>
  <%= f.input :compatibility, collection: @compatibility, as: :check_boxes, label: "Compatibility",
               input_html: { multiple: true} %>
  <% index = 0%>
  <%= f.simple_fields_for :product_images do |p| %>
    <% if p.object.new_record? %>
      <%= p.input :image, as: :file, input_html: { multiple: true, 
                  name: "product[product_images_attributes][][image]" }  %>
    <% else%>
      <% if index == 0%>
        <div class="form-group row file optional product_product_images_image" id="manage-image">
          <label class="col-sm-3 form-control-label file optional">Image</label>
            <div class="col-sm-9">
              <div class="col-sm-12 add-new-product-image">
                <%= link_to "Add New Image", new_admin_product_image_path(@product.id), 
                            class: "btn btn-success", remote: true %>
              </div>
              <div class="row">
      <% end %>
      <% index +=1 %>
      <div class="col-6 no-p-lr">
        <div class="row product-form-image <%= p.object.id.to_i == params[:failed_product_image].to_i ? 'image-error' : 'image-no-error' %>">
          <div class="col-6 no-p-lr">
            <%= image_tag p.object.image.url(:thumb), class: "img-fluid" %>
          </div>
          <div class="col-6 no-p-lr">
            <%= link_to "edit", edit_admin_product_image_path(@product.id, p.object.id),
                        class: "btn btn-primary mb-2", remote: true %>
            <%= link_to "delete", admin_product_image_path(@product.id, p.object.id),  
                        class: "btn btn-danger mb-2", :method => :delete, data: {:confirm => "Are you sure?"} %>
            <% if !p.object.is_primary %>
              <%= link_to "Set As Primary", set_as_primary_admin_product_path(@product.id, p.object.id),
                          class: "btn btn-primary mb-2" %>
            <% end %>
          </div>
        </div>
      </div>
      <% if index == f.object.product_images.size.to_i %>
            </div>
          </div>
        </div>
      <% end %>

    <% end %>
  <% end %>
  <%= f.input :short_description, as: :text, :input_html => {:rows => 7} %>
  <%#= f.input :description, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } } %>
  <%= f.input :specification, as: :text, :input_html => {:rows => 7} %>
  <%= f.input :feature, as: :text, :input_html => {:rows => 7} %>

  <%= f.input :page, :as => :hidden, :input_html => { :value => params[:page] || 1 } %>
  <div class="form-group row mb-0">
    <div class="col-sm-9 offset-sm-3">
      <%= f.button :submit, class: "btn-primary" %>
      <%= link_to "Cancel", admin_products_path(:page => params[:page]), 
                  class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>

<div id="edit-image"></div>

app/views/admin/products/edit.html.erb
<section class="admin-section-content">
  <div class="container">
    <div class="row">
      <div class="col-12 header-n-breadcrumb">
        <div class="row">
          <div class="col-12 col-md-6">
            <h2>Edit Product</h2>
          </div>
          <div class="col-12 col-md-6 align-self-center">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
                <li class="breadcrumb-item"><%= link_to "Products", admin_products_path %></li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
      <div class="col-sm-12 admin-products">
        <%= render :partial => "shared/flash" %>
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/admin/products/index.html.erb
<section class="admin-section-content">
  <div class="container">
    <div class="row">
      <div class="col-12 header-n-breadcrumb">
        <div class="row">
          <div class="col-12 col-md-6">
            <h2>PRODUCTS</h2>
          </div>
          <div class="col-12 col-md-6 align-self-center">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
                <li class="breadcrumb-item active" aria-current="page">Products</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
      <div class="col-sm-12 admin-products">
        <%= render :partial => "shared/flash" %>
        <p><%= link_to "Add new product", new_admin_product_path, class: "btn btn-primary" %></p>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Category</th>
              <th>Short Desc</th>
              <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody>
            <% @products.each_with_index do |product, x| %>
              <tr>
                <th scope="row"><%= @no+x+1 %></th>
                <td><%= product.name %></td>
                <td><%= product.try(:category).try(:name) %></td>
                <td class="p_spec">
                  <ul>
                  <% product.short_description.split("\n").each do |x| %>
                    <li><%= x %></li>
                  <% end %>
                  </ul>
                </td>
                <td>
                  <%= link_to "Feature Detail", admin_product_feature_details_path(product.id), :class => "btn btn-primary" %>
                  <%= link_to "Edit", edit_admin_product_path(product.id, :page => params[:page]), :class => "btn btn-success" %>
                  <%= link_to "Delete", admin_product_path(product.id, :page => params[:page] ), :method => :delete,
                                        data: {:confirm => "Are you sure?"}, :class => "btn btn-danger" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <div class="col-xs-12 pagination justify-content-center"><%= paginate @products %></div>
      </div>
    </div>
  </div>
</section>

app/views/admin/products/new.html.erb
<section class="admin-section-content">
  <div class="container">
    <div class="row">
      <div class="col-12 header-n-breadcrumb">
        <div class="row">
          <div class="col-12 col-md-6">
            <h2>New Product</h2>
          </div>
          <div class="col-12 col-md-6 align-self-center">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
                <li class="breadcrumb-item"><%= link_to "products", admin_products_path %></li>
                <li class="breadcrumb-item active" aria-current="page">New</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
      <div class="col-sm-12 admin-products">
        <%= render :partial => "shared/flash" %>
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
</section>